#!/bin/sh

while true
do

	CHARGE=$(cat /sys/class/power_supply/BAT0/capacity)
	STATUS=$(cat /sys/class/power_supply/BAT0/status)

    [ "$STATUS" = "Charging" ] && exit

	if (($CHARGE < 15)) ; then
	    notify-send -u critical "Low Battery"
	fi

	if (($CHARGE < 6)) ; then
	    notify-send "Hibernating in 10 seconds"
	    sleep 10
	    systemctl suspend ; slock
	fi
	
	sleep 60

done
