#!/bin/sh

#Vim stuff

alias vim="nvim"
alias svim="sudo nvim"
alias vimdiff="nvim -d"

#Git stuff

alias gs="git status"
alias gsu="git status -uno"
alias gc="git commit -m"
alias gp="git push"
alias ga="git add"

#SSH

alias \
	litc56="ssh omnilogic@150.164.32.56" \
    litc60="ssh gabriel-lara@150.164.32.60" \
    litc61="ssh grupo-omnilogic@150.164.32.61"

#Verbosity and safety

alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" 


#Conda 

alias \
	ca="conda activate" \
	cdt="conda deactivate" 
	

#Color time

alias \
	grep="grep --color=auto" \
	diff="diff --color"

#Long stuff

alias \
	ka="killall" \
	s="ddgr" \
	p="sudo pacman" \
    thm="wal -i" \
    see="sxiv" \
    mail="neomutt" \

#Disk/USB handling

alias \
	fd="sudo fdisk" \
	mount="sudo mount" \
	umount="sudo umount" \
	dnode="lsblk | grep -A 1 disk | tail -n 1" \
	dinfo="fd -l | tail -n 2"
